name: Test

on:
  push:
    branches:
      - main

jobs:
  test-sqlite:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - django: 'Django'
          - django: 'git+https://github.com/django/django.git@main#egg=Django'
          - django: 'git+https://github.com/adamchainz/django.git@ticket_35301#egg=Django'

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          pip install "${{ matrix.django }}"
      - name: Test
        run: |
          python manage.py test
